const pageName=(location.pathname.split('/').pop()||'index.html');
const nav=[['index.html','Home'],['about.html','About Us'],['services.html','Our Services'],['why-choose-us.html','Why Choose Us'],['faqs.html','FAQs'],['contact.html','Contact']];
const active=pageName.startsWith('service-')?'services.html':pageName;
const header=document.querySelector('[data-site-header]');
if(header){header.className='site-header';header.innerHTML=`<a class="brand" href="index.html" aria-label="Care Beyond Expectations home"><span class="brand-mark"><i></i><b></b><em></em></span><span><strong>CARE <span>BEYOND</span></strong><small>EXPECTATIONS</small></span></a><button class="menu" aria-label="Toggle navigation" aria-expanded="false">☰</button><nav aria-label="Main navigation">${nav.map(([u,l])=>`<a class="${active===u?'active':''}" href="${u}">${l}</a>`).join('')}</nav><a class="btn header-btn" href="contact.html">Get Support <span>→</span></a>`}
const footer=document.querySelector('[data-site-footer]');
if(footer){footer.innerHTML=`<div class="footer-brand"><a class="brand inverse" href="index.html"><span class="brand-mark"><i></i><b></b><em></em></span><span><strong>CARE BEYOND</strong><small>EXPECTATIONS</small></span></a><p>Support • Independence • Community</p></div><div><h3>Quick Links</h3><a href="index.html">Home</a><a href="about.html">About Us</a><a href="services.html">Our Services</a><a href="why-choose-us.html">Why Choose Us</a></div><div><h3>Our Services</h3><a href="service-daily-living.html">Daily Tasks / Shared Living</a><a href="service-personal-activities.html">Personal Activities</a><a href="service-life-skills.html">Life Skills</a><a href="service-community-participation.html">Community Participation</a></div><div><h3>Get In Touch</h3><p>Melbourne &amp; surrounding areas</p><a href="mailto:info@carebeyondexpectations.com.au">info@carebeyondexpectations.com.au</a></div><div class="footer-note"><strong>ndis</strong><p>Supporting NDIS participants</p></div><p class="copyright">© 2026 Care Beyond Expectations. All rights reserved.</p>`}
const menu=document.querySelector('.menu'),mainNav=document.querySelector('.site-header nav');
if(menu&&mainNav){menu.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'✕':'☰'});mainNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mainNav.classList.remove('open')))}
const form=document.querySelector('#enquiry-form');
if(form){form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const subject=encodeURIComponent(`Support enquiry from ${d.get('name')}`);const body=encodeURIComponent(`Name: ${d.get('name')}\nPhone: ${d.get('phone')}\nEmail: ${d.get('email')}\nSupport of interest: ${d.get('service')}\n\n${d.get('message')}`);location.href=`mailto:info@carebeyondexpectations.com.au?subject=${subject}&body=${body}`})}
